version: "3.7"

x-service-volumes: &service-volumes
  - ./:/app/:rw,cached

services:
  website:
    image: {{cookiecutter.project_name}}:latest
    container_name: website
    command: python manage.py runserver 0.0.0.0:8000
    volumes: *service-volumes
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - DJANGO_ALLOWED_HOSTS
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:11
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_{{cookiecutter.project_name}}:/var/lib/postgresql/data/

volumes:
  pg_{{cookiecutter.project_name}}:
