# Generated by Django 3.1.7 on 2021-02-28 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='Facebook URL', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Instagram URL', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='Linkedin URL', null=True)),
                ('twitter', models.URLField(blank=True, help_text='Twitter URL', null=True)),
                ('youtube', models.URLField(blank=True, help_text='YouTube Channel URL', null=True)),
                ('google_tag_head', models.TextField(blank=True, help_text='Aggiungi lo script di Google Tag Manager per il tag <head></head>', null=True, verbose_name='Google Tag Manager <head>')),
                ('google_tag_body', models.TextField(blank=True, help_text='Aggiungi lo script di Google Tag Manager per il tag <body></body>', null=True, verbose_name='Google Tag Manager <body>')),
                ('google_analytics', models.CharField(blank=True, help_text='Il tuo Google Analytics tracking ID (inizia con "UA-")', max_length=20, null=True, verbose_name='Google Analytics Traking ID')),
                ('facebook_pixel', models.TextField(blank=True, help_text='Aggiungi lo script di Facebook Pixel', null=True, verbose_name='Facebook Pixel')),
                ('favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favicon', to='wagtailimages.image', verbose_name='Favicon')),
                ('logo', models.ForeignKey(blank=True, help_text='Brand logo per tutto il sito', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo', to='wagtailimages.image', verbose_name='Logo')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Generale',
                'verbose_name_plural': 'Generale',
            },
        ),
    ]
