version: "3.7"

x-service-volumes: &service-volumes
  - ./:/app/:rw,cached

services:
  website:
    image: {{cookiecutter.project_slug}}:latest
    container_name: website_{{cookiecutter.project_slug}}
    command: python manage.py runserver 0.0.0.0:8000
    volumes: *service-volumes
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - DJANGO_ALLOWED_HOSTS
    ports:
      - "8000:8000"
    env_file:
    - ./.env-dev
    depends_on:
      - postgres

  postgres:
    image: postgres:11
    container_name: postgres_{{cookiecutter.project_slug}}
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - POSTGRES_PORT
    volumes:
      - pg_{{cookiecutter.project_slug}}:/var/lib/postgresql/data/

volumes:
  pg_{{cookiecutter.project_slug}}:
