version: "3.7"

x-service-volumes: &service-volumes
  - ./:/app/:rw,cached

services:
  website:
    image: wagtail_starter_project:latest # Nome del progetto
    container_name: website
    command: python manage.py runserver 0.0.0.0:8000
    volumes: *service-volumes
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:11
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_wagtail_starter_project:/var/lib/postgresql/data/ # Modifica Nome

volumes:
  pg_wagtail_starter_project: # Modifica Nome
