name: Deploy Live!

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: "./src"
          target: "/home/lorenzo/NOME-PROGETTO" # Cartella del progetto sul server

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: | # Cambia il nome della cartella & il comando per Supervisor
            cd NOME-PROGETTO/
            . env/bin/activate
            cd src/
            pip install -r requirements.txt
            python manage.py makemigrations --settings=wagtail_project.settings.production
            python manage.py migrate --settings=wagtail_project.settings.production
            python manage.py collectstatic --no-input
            deactivate
            sudo supervisorctl restart NOME-COMANDO
